apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "lagoon-core.broker.fullname" . }}
  labels:
    {{- include "lagoon-core.broker.labels" . | nindent 4 }}
spec:
{{- if not .Values.broker.autoscaling.enabled }}
  replicas: {{ .Values.broker.replicaCount }}
{{- end }}
  serviceName: {{ include "lagoon-core.broker.fullname" . }}-headless
  selector:
    matchLabels:
      {{- include "lagoon-core.broker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/broker.secret: {{ include (print $.Template.BasePath "/broker.secret.yaml") . | sha256sum }}
    {{- with .Values.broker.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "lagoon-core.broker.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lagoon-core.broker.serviceAccountName" . }}
      securityContext:
        {{- toYaml (coalesce .Values.broker.podSecurityContext .Values.podSecurityContext) | nindent 8 }}
      containers:
      - name: broker
        securityContext:
          {{- toYaml .Values.broker.securityContext | nindent 10 }}
        image: "{{ .Values.broker.image.repository }}:{{ coalesce .Values.broker.image.tag .Values.imageTag .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.broker.image.pullPolicy }}
        command:
        - sh
        args:
        - /cluster-rabbit.sh
        env:
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: {{ include "lagoon-core.broker.fullname" . }}
              key: RABBITMQ_PASSWORD
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "lagoon-core.broker.fullname" . }}
              key: RABBITMQ_USERNAME
        - name: RABBITMQ_USE_LONGNAME
          value: "true"
        # these variables are used by the /cluster-rabbit.sh entrypoint
        - name: POD_NAMESPACE
          value: {{ .Release.Namespace | quote }}
        - name: SERVICE_NAME
          value: {{ include "lagoon-core.broker.fullname" . }}
      {{- range $key, $val := .Values.broker.additionalEnvs }}
        - name: {{ $key }}
          value: {{ $val | quote }}
      {{- end }}
        ports:
        - name: epmd
          containerPort: 4396
        - name: amqp
          containerPort: 5672
        - name: http
          containerPort: 15672
        - name: metrics
          containerPort: 15692
        volumeMounts:
        - name: {{ include "lagoon-core.broker.fullname" . }}-data
          mountPath: /var/lib/rabbitmq
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -ec
            - rabbitmqctl status
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -ec
            - rabbitmqctl status
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        resources:
          {{- toYaml .Values.broker.resources | nindent 10 }}
      volumes:
      - name: {{ include "lagoon-core.broker.fullname" . }}-data
        persistentVolumeClaim:
          claimName: {{ include "lagoon-core.broker.fullname" . }}-data
      {{- with .Values.broker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.broker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.broker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: {{ include "lagoon-core.broker.fullname" . }}-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
