{{- if .Values.nats.enabled -}}
{{- if .Values.natsConfig.tls.secretData -}}
---
{{/*
This secret must have a static name because the nats subchart is configured to
use this secret via the lagoon-remote values.yaml.
*/}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: lagoon-remote-nats-tls
  labels:
    {{- include "lagoon-remote.labels" . | nindent 4 }}
stringData:
  {{- with .Values.natsConfig.tls.secretData }}
  {{- . | toYaml | nindent 2 }}
  {{- end }}
{{- end }}
---
{{/*
This secret must have a static name because the nats subchart is configured to
use this secret via the lagoon-remote values.yaml.
*/}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: lagoon-remote-nats-conf
  labels:
    {{- include "lagoon-remote.labels" . | nindent 4 }}
stringData:
  lagoon-remote.conf: |
    leafnodes {
      no_advertise: true
      remotes: [
        {
          url: {{ .Values.natsConfig.coreURL | quote }}
          tls: {
            {{- if .Values.natsConfig.tls.secretData -}}
            ca_file: "/etc/lagoon-remote-nats-tls/ca.crt"
            {{- end }}
            cert_file: "/etc/lagoon-remote-nats-tls/client.crt"
            key_file: "/etc/lagoon-remote-nats-tls/client.key"
          }
        }
      ]
    }
{{- end }}
