{{- if .Values.sshPortal.enabled -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "lagoon-remote.sshPortal.fullname" . }}
  labels:
    {{- include "lagoon-remote.sshPortal.labels" . | nindent 4 }}
stringData:
  {{- with .Values.sshPortal.hostKeys.ecdsa }}
  HOST_KEY_ECDSA: |-
    {{- . | nindent 4 }}
  {{- end }}
  {{- with .Values.sshPortal.hostKeys.ed25519 }}
  HOST_KEY_ED25519: |-
    {{- . | nindent 4 }}
  {{- end }}
  {{- with .Values.sshPortal.hostKeys.rsa }}
  HOST_KEY_RSA: |-
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
